### ISSUE TITLE
&'s are not rendered properly in PR rendering

### ISSUE THREAD

**Issue by kipz** [atomist/lifecycle-automation#11]
![screen shot 2017-10-28 at 00 55 55](https://user-images.githubusercontent.com/1865026/32129013-f79cd7a6-bb7a-11e7-89f0-f726f1104263.png)

**Comment by cdupuis** [comment]
That looks a bit like it got double escaped or so? I'll check it.

**Comment by cdupuis** [comment]
Ok, here is the underlying message that got produced:

```
{
  "text": "1 new commit to *<https://r.atomist.com/r1becJdrb0W|atomisthq/automation-api/zipper>*",
  "attachments": [{
    "author_name": "@kipz",
    "author_link": "https://r.atomist.com/ryMg5kdrW0b",
    "author_icon": "https://avatars.githubusercontent.com/kipz",
    "text": "`<https://r.atomist.com/rJNeqkOBbCb|5656dc1>` Support for field directives 'required' &amp; 'ne' :atomist_build_passed: <https://r.atomist.com/rySe5JdS-AW|Build #571>",
    "mrkdwn_in": ["text"],
    "color": "#00a5ff",
    "fallback": "1 commit to <https://github.com/atomisthq/automation-api/tree/zipper|atomisthq/automation-api/zipper> by @kipz",
    "footer": "<https://r.atomist.com/BkXe5yOr-Rb|atomisthq/automation-api>",
    "actions": [],
    "footer_icon": "http://images.atomist.com/rug/commit.png",
    "ts": 1509148449
  }, {
    "author_name": "#139: Support for field directives 'required' &amp; 'ne'",
    "author_icon": "https://images.atomist.com/rug/pull-request-open.png",
    "author_link": "https://r.atomist.com/SkUeqJ_rbRZ",
    "fallback": "#139: Support for field directives 'required' &amp; 'ne'",
    "ts": 1509148642,
    "footer": "<https://r.atomist.com/H1De9JOB-Ab|Feedback?>",
    "mrkdwn_in": ["footer"]
  }],
  "unfurl_links": false,
  "unfurl_media": false
}
```

That looks pretty ok to me. Not sure what to do about that.

**Comment by cdupuis** [comment]
https://api.slack.com/docs/message-formatting is pretty clear that we have to escape `&` to `&amp;`

**Comment by cdupuis** [comment]
@tanya-coding can you help shed some light on this?

**Comment by tanya-coding** [comment]
@cd It doesn't look like you can escape `&` in `author_name` field (even if you leave it unescaped or add it to `mrkdwn_in` list, Slack builder still shows it as `&amp;`). If we are OK loosing the issue icon we can move the issue list into text (separated by new lines):

https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%221%20new%20commit%20to%20*%3Chttps%3A%2F%2Fr.atomist.com%2Fr1becJdrb0W%7Catomisthq%2Fautomation-api%2Fzipper%3E*%22%2C%22attachments%22%3A%5B%7B%22author_name%22%3A%22%40kipz%22%2C%22author_link%22%3A%22https%3A%2F%2Fr.atomist.com%2FryMg5kdrW0b%22%2C%22author_icon%22%3A%22https%3A%2F%2Favatars.githubusercontent.com%2Fkipz%22%2C%22text%22%3A%22%60%3Chttps%3A%2F%2Fr.atomist.com%2FrJNeqkOBbCb%7C5656dc1%3E%60%20Support%20for%20field%20directives%20%27required%27%20%26amp%3B%20%27ne%27%20%3Aatomist_build_passed%3A%20%3Chttps%3A%2F%2Fr.atomist.com%2FrySe5JdS-AW%7CBuild%20%23571%3E%22%2C%22mrkdwn_in%22%3A%5B%22text%22%5D%2C%22color%22%3A%22%2300a5ff%22%2C%22fallback%22%3A%221%20commit%20to%20%3Chttps%3A%2F%2Fgithub.com%2Fatomisthq%2Fautomation-api%2Ftree%2Fzipper%7Catomisthq%2Fautomation-api%2Fzipper%3E%20by%20%40kipz%22%2C%22footer%22%3A%22%3Chttps%3A%2F%2Fr.atomist.com%2FBkXe5yOr-Rb%7Catomisthq%2Fautomation-api%3E%22%2C%22actions%22%3A%5B%5D%2C%22footer_icon%22%3A%22http%3A%2F%2Fimages.atomist.com%2Frug%2Fcommit.png%22%2C%22ts%22%3A1509148449%7D%2C%7B%22text%22%3A%22%3Chttps%3A%2F%2Fr.atomist.com%2FSkUeqJ_rbRZ%7C%23139%3A%20Support%20for%20field%20directives%20%27required%27%20%26amp%3B%20%27ne%27%3E%22%2C%22ts%22%3A1509148642%2C%22footer%22%3A%22%3Chttps%3A%2F%2Fr.atomist.com%2FH1De9JOB-Ab%7CFeedback%3F%3E%22%2C%22mrkdwn_in%22%3A%5B%22footer%22%2C%22text%22%5D%7D%5D%2C%22unfurl_links%22%3Afalse%2C%22unfurl_media%22%3Afalse%7D
