### ISSUE TITLE
Query GitHub for org webhook

### ISSUE THREAD

**Issue by ddgenome** [atomist/lifecycle-automation#110]
Do not trust GraphQL to say whether an organization webhook exists since people can remove them after they are created. Query GitHub directly.

**Comment by cdupuis** [comment]
Tried that, been there. That isn't possible with out current tokens.

**Comment by ddgenome** [comment]
The org token is not sufficient? Wouldn't it have been the org token that created the webhook?

**Comment by ddgenome** [comment]
https://github.com/atomist/lifecycle-automation/blob/1fad696b2f14b332d26bf2443b77cfe8eab702ca/src/handlers/event/channellink/ChannelLinkCreated.ts#L74-L78

**Comment by cdupuis** [comment]
No, the orgToken is not enough. It is not the one that creates the web hook.

**Comment by cdupuis** [comment]
@slimslenderslacks and I discussed the current implemented approach and agreed that we should rely on Neo for the org web hook. If the data isn't complete in neo, we got to fix this.
