### ISSUE TITLE
Atomist is not suggesting to install a repo webhook when linking a repo in personal account 

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#111]
I have enrolled a brand new team, have not chosen an org. I ran Repos command and linked a repo in my personal account but that didn't cause repo webhook to be created and bot didn't suggest to install one so any command I run there does work but no events show up in channel:

![image](https://user-images.githubusercontent.com/19268924/35002736-38a430ea-fab0-11e7-95d8-1bb1c08bfe18.png)

**Comment by cdupuis** [comment]
what is the team id of that team?

**Comment by tanya-coding** [comment]
T6CB0Q70A
