### ISSUE TITLE
Workflow charts never show completed status

### ISSUE THREAD

**Issue by claymccoy** [atomist/lifecycle-automation#112]
I can't find an example where this is actually happening.

When I search logz.io with this query `operation-name:StatusToPushLifecycle AND "image_url"` I can see all chart URLs as they were updated. Every one of these seems to eventually finish. Most of them in in a failure state due to the "verify" or "orders" job but that is a correct representation of what is happening.

If I look at a workflow in Neo and the builds attached to it, I can find one where everything completed:
`match (n: Workflow) where n.id="T0CG5J074_7571ab4f-fd5d-49da-b78f-d5c03faa82e1" return n`

If I take that workflow config, and all of its builds:
`$match (n: Build) where n.workflowId="7571ab4f-fd5d-49da-b78f-d5c03faa82e1" return n`
and I put that data into the ChartWorkflowTest.ts and then put that output into ChartUrlTest.ts then I get the completed workflow chart that I would expect:
`https://image-charts.com/chart?chs=400x140&cht=bhs&chd=t:79,20,88,54%7C0,0,235,0%7C0,0,0,0%7C0,0,0,0&chds=a&chco=0FA215,86DB95,DD5B6A,E9D139&chxt=x,y&chxl=0:%7Csvc_base_img%7Cdeps_complete%7Ccampaigns%7Cdev_deploy%7C&chtt=Workflow%2520Stage%2520Durations%2520`

The only way that I have found to make the chart show an unfinished workflow is to remove some of the passed build nodes, which is how it is supposed to work. I haven't found any flaw int he logic that would cause the data to be misrepresented as an uncompleted workflow

**Comment by ddgenome** [comment]
Example: Invocation Id: b01a416e-5936-407e-8dce-258f24617fc9

**Comment by claymccoy** [comment]
This is the one that we already investigated. Workflow "7571ab4f-fd5d-49da-b78f-d5c03faa82e1" which completed successfully.

**Comment by claymccoy** [comment]
If I look at all the logs around this for a two hour period, I never see another log for a StatusToPushLifecycle that updates this workflow. But there are build nodes in neo that would have taken place after this. Why did they not produce any results? Did we have some downtime at this point in time?
Specifically this represents Build node with id="T0CG5J074_circle-tuup/tuup-platform-7773" in Neo. There were 13 Builds that passed after that according to Neo. Where are they in the logs?
This is why I was asking for more data. All I can tell from this is that the code was doing the right thing with the data that it had.

**Comment by cdupuis** [comment]
There are couple of incoming Builds that have incomplete data (missing repo, commits etc). The problem is likely somewhere else in the backend:

Invocation Id: aa5dd3c7-5a86-43a9-8d10-535c0b5fbb97
