### ISSUE TITLE
Send cluster/worker to logz.io

### ISSUE THREAD

**Issue by cdupuis** [atomist/lifecycle-automation#119]
With the recent changes to dump-init the reporting in logz.io is broken. We now need to send a key/value to indicate which log statement is from master etc.

**Comment by ddgenome** [comment]
Can you provide more information about the issue? How did running node from dumb-init break things? We can remove it, I just thought it would be safer since multiple workers are being spun up.

**Comment by cdupuis** [comment]
I reporting was _assuming_ that the stats would come from pid `1` which used to be the master node. But that was naive to beginn with. I'll fix this proper. 

We shouldn't roll the dump-init change back; instead fix my naive implementation. Two line change.
