### ISSUE TITLE
not able to create a project-level webhook

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/lifecycle-automation#12]
- when there are no authorized orgs
- I use "@atomist install webhook"

the bot asks me for an org and then assumes that I must have >0 orgs enrolled.  I would like to install a webhook in one of my authorized User's personal orgs.

**Comment by slimslenderslacks** [comment]
<img width="1093" alt="screenshot 2017-10-27 19 37 15" src="https://user-images.githubusercontent.com/1643888/32130518-befd3020-bb4e-11e7-8c67-9e9b69fc66f1.png">

**Comment by slimslenderslacks** [comment]
This command must work even when there are no orgs enrolled in the slack team.  For example, after I run a generator and create something in my own user account.

**Comment by cdupuis** [comment]
Hmm, I assume this is because the owner is a mapped parameter and the bot insists of filling it in. 

I can make owner a normal parameter so that the user can fill this in. Ok? cc @slimslenderslack

**Comment by WillGardella** [comment]
Was the owner a mapped parameter to prevent impersonation?

**Comment by cdupuis** [comment]
No, that’s just convinience to not have to type the org. You can’t install a web hook into a repo for which you don’t have access rights. There is no impersonation possible here.

**Comment by slimslenderslacks** [comment]
I'm now sort of convinced that @cdupuis  is right and we really should be updating the MappedParameter validation logic to allow a user to select their own personal Org.  This is very much an acknowledgement that this channel has been "linked" to a Repo from their own personal account.  And this link step can only be done from a Slack user that has successfully authorized this account.

**Comment by slimslenderslacks** [comment]
Closing because I've moved this to an issue on the Mapped Parameter side
