### ISSUE TITLE
Lifecycle needs to migrate away from using GitHubOrgWebhook

### ISSUE THREAD

**Issue by whostolebenfrog** [atomist/lifecycle-automation#129]
`GitHubOrgWebhook` is very misleading. As such we are migrating to a new node label of `Webhook`.

All existing nodes have had the additional label applied, and an additional system event is being raised of type `Webhook`. Whilst we migrate both nodes will exist in the DB and schema.

The `Org` node, which is the only node to have a relationship to the `GitHubOrgWebhook` now also has a relationship to `Webhook`. I also took this chance to make this `webhooks` and previously it had a 1:* relationship with a singular name of `webhook`. That was helpful actually!

```idl
type Webhook  {   
       atmTeamId: String,
       id: ID,
        url: String,
        org: Org @relation(name: "HAS", direction: "IN"),
        webhookType : WebhookType,
    }
```

```idl
type Org  { 
       atmTeamId: String,
       id: ID,
        owner: String,
        provider: GitHubProvider @relation(name: "FROM"),
        repo: [Repo] @relation(name: "HAS"),
        webhook: [GitHubOrgWebhook] @relation(name: "HAS"),
        webhooks: [Webhook] @relation(name: "HAS"),
        chatTeam: ChatTeam @relation(name: "OWNS", direction: "IN"),
        ownerType : OwnerType,
        team: Team @relation(name: "OWNS" direction: "IN"),
    }
```

**Comment by ddgenome** [comment]
@whostolebenfrog should the `WebhookType` enum be expanded to allow for non-GitHub webhooks? I like this change but my concern is once we start tracking BitBucket or other webhooks, the types "organization" and "repository" will become ambiguous. Perhaps we should add "GitHubOrganization" and "GitHubRepository"? Or do you think Webhook.url should be used to disambiguate?

**Comment by ddgenome** [comment]
We've decided to remove the GitHubOrgWebhook node and events entirely, so lifecycle-automation needs to now subscribe to the events and not query GraphQL for them. This means these changes are needed, per @whostolebenfrog:

-   Change to query the github api rather than neo for Org webhooks
-   Move the message from the GitHubOrgWebhook handler to the handler that creates the webhook.

**Comment by cdupuis** [comment]
We don't use the web hook functionality in lifecycle any longer. This was removed.
