### ISSUE TITLE
Label issues with deployment environment name

### ISSUE THREAD

**Issue by kipz** [atomist/lifecycle-automation#135]
It would close the loop nicely if labels could be added to issues when related "fixes/resolves" pushes or commits make it a new environment (or are otherwise released).

It might make sense for this to be a separate automation because lifecycle already shows labels, and such an automation could be very loosely coupled, except that it relies on the deployment/application stuff.

**Comment by slimslenderslacks** [comment]
I feel like there are two companion pieces to this really working:
1.  environment labels need to be managed.  Available in all repos or at least can be added dynamically if they're missing.
2.  doesn't this all rely on having good commit--issue links?  Or at least it becomes most useful once you're confident that your issues all end up linked to one commit that is an ancestor of the master ref.  How do best facilitate that?
- when is the right time to check whether a Push resolves one of your assigned Commits?
- branch commits can be rewritten in weird ways
- a Push to master where none of the Commits have linked Issues is one opportunity
- a Push to master with linked Commits, but other assigned Issues not linked, might be a good opportunity to ask again
- I think we want to encourage people to use Issue assignments.

**Comment by jessitron** [comment]
i think repo label management belongs in the SDM.
It is a team/corporate policy

**Comment by cdupuis** [comment]
Yeah, probably.

**Comment by cdupuis** [comment]
I have most of this implemented with custom events and are now stuck at the point of actually creating the labels on GitHub due to the fact that we don't send org tokens for custom event subscriptions. Until this is addressed I'm going to pause this here.

**Comment by cdupuis** [comment]
This has been move to sdm-pack-issue.
