### ISSUE TITLE
Image attachement regex can go into endless loop

### ISSUE THREAD

**Issue by cdupuis** [atomist/lifecycle-automation#136]
Added failing test to show this: https://github.com/atomist/lifecycle-automation/commit/b31cc7ad5619f10d0a1f33608fd818067439b34d

**Comment by ddgenome** [comment]
Some reference material:

-   https://blog.codinghorror.com/the-problem-with-urls/
-   https://www.regular-expressions.info/catastrophic.html
-   https://www.regular-expressions.info/possessive.html
-   https://www.regular-expressions.info/atomic.html
-   https://www.regular-expressions.info/javascript.html

**Comment by ddgenome** [comment]
Try to fix this without undoing this: https://github.com/atomist/lifecycle-automation/commit/d6ad2580f40eb2205fc3cfae921e01af80189126
