### ISSUE TITLE
Allow other merge strategies for the Auto merge functionality

### ISSUE THREAD

**Issue by donovanmuller** [atomist/lifecycle-automation#144]
Currently after clicking the _Auto merge_ button on a Pull Request message, the PR will be merged once all conditions have been met.

Currently, the 'Create a merge commit' merge strategy is used to auto merge.
It would be nice to have the option to choose another merge strategy:

![screen shot 2018-02-21 at 11 25 35](https://user-images.githubusercontent.com/1175891/36472302-21796262-16fa-11e8-9e93-261db41d4317.png)

**Comment by cdupuis** [comment]
Auto merge method can now be defined by using a special label on the PR. 

Use `@atomist add auto merge labels` to add the labels to your repository.
