### ISSUE TITLE
use setOwnerLogin mutation during GitHub Org registration

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/lifecycle-automation#152]
Just creating the org webhook is not enough!

@hen we install an Org-Level Webhook today, the automation client uses the GitHub api to create the Webhook.  Our bot-based enrollment also used to use this opportunity to record the login token used to create this Webhook so that future event handlers could look up 
`github://org_token` when they need to operate against Org resources but are not running in a user context.

In the web-based flow, especially when there is no bot, the burden of recording the login token has to shift.  We have created a graphql mutation to do this:  

```
mutation {
  setOwnerLogin(owner: "", providerId: "", login: "") {
    login
  }
}
```

The owner is he name of an GitHub org (ie atomisthqa).  The login is a gitHub login that has already authorized Atomist.  

* The mutation will fail if the login is for a gitHub user that has not already authorized Atomist
* The mutation will also fail if the login is for a user that is not a member of the GitHub organization identified by owner/providerId.

Without this step, all downstream attempts to lookup github://org_token` will fail.

**Comment by cdupuis** [comment]
@slimslenderslacks tested this and it calls the mutation with the correct parameters. I can't validate the backend. handing back over to you.
