### ISSUE TITLE
Unable to link/unlink existing repo in staging

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#154]
I'm getting an error message coming from lifecycle-automation: ```The repository `atomisthqa/handlers` either does not exist or you do not have access to it.```

I've verified using my token that I do have access to the repo.

Example correlation ID: 0c27b3cd-2a12-43fd-8162-f5d5a9ad452e

**Comment by cdupuis** [comment]
This seems to be a bug in the latest release of @octokit/rest. Investigating.
