### ISSUE TITLE
inviteUserToSlackChannel mutation fails to invite user to private channel

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#155]
Bot fails to ensure channel existence for private channels and it will also fail to invite team members if Atomist team owner is not in the channel. We should research if we can use bot user to invite members if bot is in the channel.

**Comment by cdupuis** [comment]
@tanya-coding why was that raised here?

**Comment by tanya-coding** [comment]
@cdupuis so we can track it in a public repo, where shall I move it? There is an internal issue open in bot but I'd like to have a customer facing bug.

**Comment by tanya-coding** [comment]
I've investigated this some more and the issue is caused by the fact that neither Atomist application nor Atomist admin user have `groups:write` Slack scope to invite other members. We don't necessarily want to request more scopes when enrolling our bot. A better fix would be to introduce collection of Slack user authorizations so channel management commands can be run as those users rather than as bot or Atomist team owner. This would be similar to GutHub authorization and would allow some action attribution for channel/group management. This also makes it possible for us to be more specific and only require extra scopes when there are needed.
