### ISSUE TITLE
Show more then 5 phases

### ISSUE THREAD

**Issue by jessitron** [atomist/lifecycle-automation#156]
When all statuses have passed and they condense to '5 completed checks' then we are sad because we cannot get to the prerelease artifact. Please continue to show that one. cc <@U2KC5KF3L>

**Comment by jessitron** [comment]
ah, it didn't translate :-)  just checking.

cc @johnsonr

**Comment by cdupuis** [comment]
It is Slack suppressing anything that is longer then 5 lines. Not lifecycle. If we want to change that I can do it but will come with a price.

**Comment by cdupuis** [comment]
Do you have a screenshot or link? I have the feeling you’re talking about something else?

**Comment by jessitron** [comment]
no, no! it only said one line! hold on I'll get one

**Comment by cdupuis** [comment]
The pre-release status is always available on the Push. We don’t condense there. Showing them on PRs too feels duplicating a lot of information.

**Comment by jessitron** [comment]
ok I guess we'd have to create a PR ... ok, so we need to find the Push request there? this frustrated Rod yesterday

**Comment by jessitron** [comment]
I'll show it to him

**Comment by cdupuis** [comment]
We only show expanded statuses on Push. PR only has the summary.
