### ISSUE TITLE
'Stop for all repos' on unmapped-repo-commit notification fails

### ISSUE THREAD

**Issue by kipz** [atomist/lifecycle-automation#161]
https://atomist-community.slack.com/archives/C9CFTQT97/p1519647218000294

**Comment by allanyung** [comment]
> This is the last time I will ask you about ORG/REPO. You can stop receiving similar suggestions for all repositories by clicking the button below.
￼
All Repositories

Clicking the All Repositories button does not prevent the bot from asking when it notices commits to other repos. Though you do get the confirmation that you have changed the config

> [:tick:] Successfully updated your preferences
mapRepo direct messages disabled

**Comment by cdupuis** [comment]
Turns some of our queries don't return the expected data for user preferences. @kipz is going to investigate and update here once we know what is going on.

**Comment by kipz** [comment]
The issue was in the API, not here. We've just deployed it to a testing environment. I'll update here once it's been verified and deployed to production.

**Comment by kipz** [comment]
This is resolved and confirmed by @allanyung
