### ISSUE TITLE
Create [channel] button truncates long repo names

### ISSUE THREAD

**Issue by allanyung** [atomist/lifecycle-automation#162]
When the bot prompts you to create a new channel for a detected commit to a new repo, it truncates long names. I don't want to reveal our private repo names publicly, but have sent a screenshot to @kipz

**Comment by ddgenome** [comment]
Slack has a limit of 21 characters for channel names, which we apply when suggesting a channel name. Is this what you are seeing?

https://get.slack.help/hc/en-us/articles/201402297-Create-a-channel

**Comment by allanyung** [comment]
Hah, that is exactly what this is! It just so happens that the 22nd char is a hyphen in the repo names, so it looked like it was potentially some kind of splitting issue. Cheers
