### ISSUE TITLE
Confusing hello message are inviting bot to channel

### ISSUE THREAD

**Issue by kipz** [atomist/lifecycle-automation#167]
- name of bot is wrong
- a repo is show twice

I get that these could just be manifestations of other issues in other components, but this is what I saw after enrolling a newt team.

**Comment by kipz** [comment]
![repo_shown_twice_after_invite](https://user-images.githubusercontent.com/1865026/36857991-d3743244-1d71-11e8-8272-ff76c4efea3f.png)

**Comment by cdupuis** [comment]
Actually your bot is named `atomista` in this team. You can see it on the screenshot. I don't think that is bug, or is it @kipz?

I'll fix the duplicate channel name thing.
