### ISSUE TITLE
Renaming labels in github leads to both old and new in dropdown

### ISSUE THREAD

**Issue by jessitron** [atomist/lifecycle-automation#168]
in the issue lifecycle message, the dropdown has both 'bear' and 'release:bear' after I renamed the former to the latter in github-sdm. GitHub displays only the latter

**Comment by jessitron** [comment]
this is very minor, low priority

**Comment by cdupuis** [comment]
Lifecycle isn't reading labels form GitHub but from GraphQL. Please raise an internal bug for that.
