### ISSUE TITLE
when someone tries to merge a PR they can't see, tell them that

### ISSUE THREAD

**Issue by jessitron** [atomist/lifecycle-automation#176]
<img width="316" alt="screen shot 2018-03-05 at 9 44 41 am" src="https://user-images.githubusercontent.com/1149737/36968257-f64862aa-2059-11e8-937a-19f1c9951aa1.png">

Rod clicked merge, and looks like he wasn't on the repo (and wasn't an owner yet; we're all owners of gh orgs but most people aren't), and it gave this Not Found error. Can we tell the person more? so they know it's not an Atomist error?

**Comment by cdupuis** [comment]
That's once again all we are getting from github for this.

**Comment by cdupuis** [comment]
Will be fixed with #180
