### ISSUE TITLE
More specific error message when user doesn't have rights to close an issue

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#177]
"Must have admin rights to Repository.." might be confusing. We could make it more specific and targeted at user that is attempting the action: `@username, you don't have permissions to close this issue` or something along these lines.

![image](https://user-images.githubusercontent.com/19268924/36981757-958f3cb4-2053-11e8-8528-d3416311050f.png)

cc: @WillGardella

**Comment by cdupuis** [comment]
this will be fixed with #180
