### ISSUE TITLE
RepoOnboarded event is available

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/lifecycle-automation#179]
An example event subscription would be:

```
subscription Elmo {RepoOnboarded {repo {name owner org {id}}}}
```

and the resulting payload when this is raised will be:

```
{:data {:RepoOnboarded [{:repo {:owner "atomisthq"
                                :org {:id "T095SFFBK_zjlmxjzwhurspem"}
                                :name "pochta"}}]}
 :extensions {:correlation_id nil
              :team_id "T1L0VDKJP"
              :operationName "Elmo"
              :team_name nil}}

```

The purpose of this event is to signal to the automation that a Repo has been populated with:
- recent commits on master
- recent Issues
- recent PullRequests
and the system is ready to be queried.  The subscription itself can probably be extended to pull in more of this data OR a separate graphql data can be used.

**Comment by cdupuis** [comment]
The subscription on `RepoOnboarded` should query the repo for a recent commit and create a Push card, same for issue and PR.

Especially for the commit card, we'll query the commit and create an artificial Push with just this one commit and hand this off to the `PushLifecycle` handlers.

**Comment by slimslenderslacks** [comment]
In the Atomist staging environment, new Repo Webhooks are raising this Event now.

**Comment by cdupuis** [comment]
The event is now being consumed and we querying for commits for now. Issues and PRs to follow once this is ready.

**Comment by cdupuis** [comment]
in master now with 557f74a66832f586993c83445cd710784d696637
