### ISSUE TITLE
Show latest release / tag when tag or release action triggered

### ISSUE THREAD

**Issue by jrday** [atomist/lifecycle-automation#188]
In order to know what the current release or tag is, so that I can properly increment it, it would be helpful to show the latest in a message. Perhaps something like this:

```
Latest tag: 5.1.3
Enter a new tag to create
```

Here's an example of current tag message:

![screen shot 2018-03-19 at 10 59 35](https://user-images.githubusercontent.com/774714/37613297-e4710378-2b64-11e8-911b-99e94dc5c079.png)

**Comment by cdupuis** [comment]
Parameter meta data (including description) is defined statically at registration time. Currently we can't add dynamic text to it. So we would have to come up with something else. I'm going to look into this.
