### ISSUE TITLE
Display an error message when user attempt to link a repo to a direct message channel

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#19]
In a DM with atomist user can run `repo` command which will report success but messages won't actually be delivered in a DM. We should show an error message suggesting user to link a regular public or private channel instead

**Comment by tanya-coding** [comment]
@ddgenome should we close this now that you have #35

**Comment by ddgenome** [comment]
Sorry forgot about this one. The other one is a bit more generic. Let's just leave them both open until the new version gets released.
