### ISSUE TITLE
Linking a bitbucket based repo

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/lifecycle-automation#195]
Issue moved from atomisthq/bot-service#883

Created by @slimslenderslacks at 2018-04-04T01:20:50Z:

A lot is working but there are still some issue:
1.  after setting up the bitbucket webhook and ingesting a push, things look good in the model
... 
```
"orgs": [
          {
            "owner": "slimslenderslacks",
            "ownerType": "user",
            "repo": [
              {
                "name": "jimtest"
              }
            ],
            "scmProvider": {
              "providerType": "bitbucket_cloud"
            }
          },
```
that's the expected data so it's getting ingested.

However, this is not useful until we can link a Channel to this Repo.

Step1 of using the repo command is working well
![image](https://user-images.githubusercontent.com/1643888/38283516-38e9c234-376b-11e8-92e0-c62e5877f15a.png)
This is great - we are breaking down the orgs by github.com and bitbucket.  Nice work @tanya-coding!
But then we are validating that the repo exists before allowing a submission and we may need to soften this to a warning that we couldn't validate the repo.  
![image](https://user-images.githubusercontent.com/1643888/38283542-5f9efd68-376b-11e8-9da7-2b8ccddb7a2c.png)

this is an issue during the splunk evaluation as well because they are setting up webhooks in private repos but NOT allowing us to access them.  There's actually a lot we can do in that configuration if we allow the channel link to be created despite not being able to validate it.

---
Comment by @slimslenderslacks at 2018-04-04T02:05:17Z:

should be possible to run the channel link mutation manually:
```
mutation thing {
  linkSlackChannelToRepo(chatTeamId: "T1RCET8RF", channelId: "CA0SYLEJH", owner: "slimslenderslacks", repo: "jimtest", providerId: "bitbucketcloud") {
    id
  }
}```
but this does not seem to work and the correlation-id does not seem to be traversing to neo.

---
Comment by @cdupuis at 2018-04-04T04:16:31Z:

The image you attached is from lifecycle. I have the feeling that this validation is actually lifecycle.

---
Comment by @slimslenderslacks at 2018-04-04T04:17:28Z:

okay, moving to lifecycle

**Comment by cdupuis** [comment]
Ok, this is working now in lifecycle but there are some issues in the backend which prevent this to be tested end-to-end. Leaving this open until we can test.

**Comment by slimslenderslacks** [comment]
Need to reopen this one - i'm still seeing the same failure in staging.  I can get the backend to work correctly if I call the mutation directly but this bug is still preventing an end-to-end test using the bot.

**Comment by cdupuis** [comment]
@slimslenderslacks lifecycle isn't seeing the values it is expecting and what was previously discussed. For bitbucket cloud we get `bitbucketcloud` in the provider mapped parameter; for that bitbucket server repo we are getting the providerId. 

```
{
  "mapped_parameters": [{
    "name": "teamId",
    "value": "T6G4G4B4G"
  }, {
    "name": "channelId",
    "value": "CAF732DS6"
  }, {
    "name": "channelName",
    "value": "bitbucket54-slim-test"
  }, {
    "name": "owner",
    "value": "SLIM"
  }, {
    "name": "apiUrl",
    "value": "http://bitbucket-server-54.atomist.com:7990/"
  }, {
    "name": "provider",
    "value": "7cq796lgw39rlsi"
  }, {
    "name": "name",
    "value": "bitbucket54-slim-test"
  }],
  "secrets": [{
    "uri": "github://user_token?scopes=repo",
    "value": "d**************************************0"
  }],
  "command": "LinkRepo",
  "source": {
    "user_agent": "slack",
    "slack": {
      "team": {
        "id": "T6G4G4B4G",
        "name": "atomista-multiorg"
      },
      "channel": {
        "id": "CAF732DS6",
        "name": "bitbucket54-slim-test"
      },
      "user": {
        "id": "UA3M79URH",
        "name": "jim"
      },
      "thread_ts": "1524949687.000015"
    }
  },
  "correlation_id": "8f292a9a-255c-43d6-b3bb-437099a97622",
  "team": {
    "id": "A4EOI5D1E",
    "name": "atomista-multiorg"
  },
  "automation": {
    "name": "@atomist/lifecycle-automation",
    "version": "0.6.1-20180425193717"
  },
  "api_version": "1",
  "parameters": []
}
```

Based on that value we are checking the repo existence via API call. 

What I need to know now: is the `atomist://github/repository/provider` mapped parameter supposed to be the providerId or providerType. I guess it is probably the latter in which case I can run another query  to get to the provider type.

**Comment by cdupuis** [comment]
@slimslenderslacks this is working now in the staging team you mentioned. why did you re-open again?

**Comment by slimslenderslacks** [comment]
atomist://github/repository/provider is the provider id.  "bitbucketcloud" is actually the id we gave to all providers of bitbucket_cloud type (there will be only one per team).  For bitbucket type providers, provider id will be different for each bitbucket server instance.

**Comment by slimslenderslacks** [comment]
Oh okay, I was re-opening to answer the question.
