### ISSUE TITLE
Wrong person notified when issue is closed

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#197]
I got a DM about an issue that Jim closed:

![image](https://user-images.githubusercontent.com/19268924/38310836-2ec6c644-37e3-11e8-924f-e9d7b9e9e1fe.png)

**Comment by cdupuis** [comment]
That’s not lifecycle.

**Comment by tanya-coding** [comment]
@cdupuis where should this issue be?

**Comment by cdupuis** [comment]
Issue moved to atomist/github-sdm#299
