### ISSUE TITLE
Mentions lead to two slack notifications

### ISSUE THREAD

**Issue by whostolebenfrog** [atomist/lifecycle-automation#205]
One mention in the channel and one as a DM. How can we avoid this? Do we need the DM? I suppose it's a good backup if they have @mentions disabled for the channel but that sounds like a fairly uncommon scenario.

From Tmo:

> As a note to the above, it is sort of annoying that I get a slack notif for both the DM and the mention in the channel. Not sure how this could be mitigated though.

**Comment by giorgiosironi** [comment]
As a user, I experienced this. It is in fact noisy, but a DM has a higher priority for me than a channel; hence it's easy to miss a mention in the midst of the channel notifications while a DM guarantees it will be noticed.

**Comment by cdupuis** [comment]
I'm not sure what to do about this. Any suggestions?

**Comment by whostolebenfrog** [comment]
It's tricky.

We can suppress channel notifications right?

How about a global preference to allow you to switch between either channel notifications or DMs. Personally I'd choose the channel mentions.
