### ISSUE TITLE
UserPreferences for direct messages do not seem to be persisting

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#223]
Issue moved from atomisthq/automation-api#460

Created by @cdupuis at 2018-06-11T14:43:47Z:

Issue moved from atomist/lifecycle-automation#222

Created by @whostolebenfrog at 2018-06-11T13:27:56Z:

When I run

`@atomist configure direct messages` and disable a choice, if I then run `@atomist configure direct messages` again the choice has not been persisted. 

I just made a change to remove the old `UserPreferences` stuff from the schema but this was happening both before and after so that's more of an FYI :-)

---
Comment by @cdupuis at 2018-06-11T14:41:20Z:

I looked at this a bit and here is what I'm seeing. Running the following mutation

```
mutation SetChatUserPreference($teamId: String!, $userId: String!, $name: String!, $value: String!) {
  setChatUserPreference(chatTeamId: $teamId, chatUserId: $userId, name: $name, value: $value) {
    name
    value
  }
}
```
with variables
```
{"teamId":"T1L0VDKJP","userId":"U1L22E3SA","name":"dm","value":"{\"disable_for_build\":true,\"disable_for_assignee\":false,\"disable_for_mention\":true,\"disable_for_prUpdates\":false,\"disable_for_mapRepo\":true}"}
```
returns
```
{
  "data": {
    "setChatUserPreference": [
      {
        "name": "dm",
        "value": "{\"disable_for_build\":true,\"disable_for_assignee\":false,\"disable_for_mention\":true,\"disable_for_prUpdates\":false,\"disable_for_mapRepo\":true}"
      }
    ]
  },
  "extensions": {
    "operationName": "SetChatUserPreference",
    "correlation_id": "e202bef7-79d8-4460-aedb-e36f87366fe8"
  }
}
```

But subsequent queries return the old data:
```
query SetChatUserPreference($userId: String!) {
  ChatId(userId: $userId) {
    preferences {
      name
      value
    }
  }
}

{
  "data": {
    "ChatId": [
      {
        "preferences": [
          {
            "name": "test",
            "value": "{\"disable_for_test\":true}"
          },
          {
            "name": "dm",
            "value": "{\"disable_for_build\":false,\"disable_for_assignee\":false,\"disable_for_mention\":true,\"disable_for_prUpdates\":false,\"disable_for_mapRepo\":true}"
          }
        ]
      }
    ]
  },
  "extensions": {
    "operationName": "SetChatUserPreference",
    "correlation_id": "163681fb-2b76-4380-9c59-661b47f72f47"
  }
}
```

**Comment by tanya-coding** [comment]
@cdupuis @whostolebenfrog `setUserPreferences` mutation is expecting `chatId->id` not `chatId->userId`. So when we read data back and attempt to link preferences based on `id` we are not finding  value that we've just written using wrong `userId`. id looks like `T095SFFBK_U1782HLSU` instead of just `U1782HLSU`.

**Comment by cdupuis** [comment]
@tanya-coding so that got changed without communicating it back. I’ll change it.

**Comment by tanya-coding** [comment]
@cdupuis I suspect it got inadvertently changed when we migrated away from storing preferences in neo4j. @kipz might have a bit more insight. If it makes more sense to use `chatId -> userId` we could also fix it on back end side!
