### ISSUE TITLE
Hyperlinks containing __something__ are mangled incorrectly

### ISSUE THREAD

**Issue by kipz** [atomist/lifecycle-automation#232]
The following link:

https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/buildClientSchema-test.js#L821

Get's rendered in slack like this:

https://github.com/graphql/graphql-js/blob/master/src/utilities/*tests*/buildClientSchema-test.js#L821

and can't be followed (link broken too)

**Comment by cdupuis** [comment]
I think that is actually a bug in the markdown conversation of `slack-messages`.

**Comment by cdupuis** [comment]
Issue moved to atomist/slack-messages#36
