### ISSUE TITLE
"install webhook" command should trigger channel link flow if successful

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/lifecycle-automation#24]
Two things on this one:
1.  we would like the intent to be "install github webhook"
2.  if the webhook is created successfully, then we would like the bot to ask the user whether they'd like to link this repo to a channel.

**Comment by cdupuis** [comment]
Can we change the `intent org-webhook`? Also what about all the other intents? `create issue` should that become `create github issue`? Feels a bit inconsistent.

**Comment by cdupuis** [comment]
I’ll just add `install github webhook` and `create github issue` as additional intent.

**Comment by slimslenderslacks** [comment]
@cd Ya, you're probably right about the inconsistency.  I'm being really picky about only the things that will be visible to someone going through the blog post.  It feels like "create issue" can dispatch on things we know about a team's issue tracker.  But most teams will have different kinds of webhooks.  However, we could create a parameter of "type" when we support different kinds of webhooks.  So for now, maybe we should forget about "create github issue" and just stick with "create issue".
