### ISSUE TITLE
Requiring github auth for "@atomist link repos" when it's a bitbucket only team

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/lifecycle-automation#243]
https://github.com/atomist/lifecycle-automation/blob/e14c322dc3994e8b0507eecb09f86d9a47a94943/src/handlers/command/slack/LinkRepo.ts#L99

I think this is coming up at a customer because they really are not requiring users to have github accounts, and all of the Repos they're linking are bitbucket repos.

**Comment by cdupuis** [comment]
@slimslenderslacks that is now in staging for you test.
