### ISSUE TITLE
Show "Raise PR if successful" button when pushing to a branch

### ISSUE THREAD

**Issue by kipz** [atomist/lifecycle-automation#244]
I often end up going to Github to raise a PR for a build I know is going to pass (well, like 99% of the time), because Github allows me to do it regardless of build status. 

It interrupts my flow to wait for the build to pass then click the raise PR button.

**Comment by cdupuis** [comment]
I could probably make that button configurable to always show. Would that work? Or just remove the check for successful builds or goals. WDYT?

**Comment by kipz** [comment]
_ideally_, it would only initiate the raise PR flow _if_ the build succeeds, asking me for assignee etc. I guess that would be another label [raise-pr-on-success]. However, I'd be fine with just showing the button always.

**Comment by cdupuis** [comment]
hmm, that is interesting. We could create a new DM that comes in, when the build in that branch succeeds. Offering to assign reviewer etc.
