### ISSUE TITLE
Selecting repo from drop-down list when creating a channel doesn't link that repo

### ISSUE THREAD

**Issue by neilprosser** [atomist/lifecycle-automation#247]
Selecting repo from drop-down list when creating a channel doesn't link that repo.

**How to Reproduce:**

1. Create channel matching the name of a repo already in the organisation and invite `@atomist` at the same time.
1. We're presented with a button which (I think) lists some sort of suggested repo (based on the channel name), a drop-down containing all repos and the 'No thanks' button.
1. Choose the repo from the drop-down.

**Expected behavior:**

Atomist links the repo selected from the drop-down to the channel.

**Observed behavior:**

Nothing happened. The message goes away. Using `@atomist repos` shows nothing linked.

**Screenshots and GIFs**

<img width="596" alt="screenshot 2018-09-26 at 15 50 23" src="https://user-images.githubusercontent.com/231666/46088411-461e7a80-c1a4-11e8-8151-20dfa47a6a72.png">

<img width="685" alt="screenshot 2018-09-26 at 15 50 44" src="https://user-images.githubusercontent.com/231666/46088421-4ae32e80-c1a4-11e8-80e6-14a0a1a0287c.png">

<img width="751" alt="screenshot 2018-09-26 at 15 51 02" src="https://user-images.githubusercontent.com/231666/46088428-4e76b580-c1a4-11e8-8df6-20c45f35fc7c.png">

<img width="414" alt="screenshot 2018-09-26 at 15 51 34" src="https://user-images.githubusercontent.com/231666/46088435-520a3c80-c1a4-11e8-9765-1e332c41c6c8.png">

<img width="409" alt="screenshot 2018-09-26 at 15 51 46" src="https://user-images.githubusercontent.com/231666/46088443-546c9680-c1a4-11e8-85b3-a84a291e73ab.png">

<img width="577" alt="screenshot 2018-09-26 at 15 52 26" src="https://user-images.githubusercontent.com/231666/46088458-5afb0e00-c1a4-11e8-9dab-59c1b3ada05e.png">

**Project version:** N/A
**Atomist CLI version:** N/A

**Comment by ddgenome** [comment]
Strangely, both the button and the dropdown ultimately use the same command handler.

**Comment by ddgenome** [comment]
I see the mutation being called. Looking into why it did not successfully with @slimslenderslacks .

**Comment by cdupuis** [comment]
Could that be because of the workspaceId being sent and put into the mutation?

**Comment by ddgenome** [comment]
It looks like the team ID is not getting populated at all, but the Atomist/Slack workspace ID confusion may prevent us from fixing it.

**Comment by neilprosser** [comment]
@ddgenome - Yes. I think I tried it after clicking "Link Repository" and that worked.

**Comment by ddgenome** [comment]
LinkOwnerRepo should  be fixed now, but CreateChannel is misbehaving:

```
2018-10-01T14:35:28.934Z [m:78817:7eb94b5c-87d0-440a-b6ac-59b8ae6c7171:atm-looking-for-freedom:CreateChannel:1835] [info ] Finished invocation of command 'CreateChannel': {"code":1,"correlation_id":"dd26751d-c7b2-4468-9cf6-082311b041d8","invocation_id":"7eb94b5c-87d0-440a-b6ac-59b8ae6c7171","message":"Network error:
Response not successful: Received status code 400","stack":"Error: Network error: Response not successful: Received status code 400\n    at new ApolloError (/Users/dd/develop/atomist/lifecycle-automation/node_modules/src/errors/ApolloError.ts:56:5)\n    at Object.error (/Users/dd/develop/atomist/lifecycle-automation/node_modules/src/core/QueryManager.ts:300:13)\n    at notifySubscription (/Users/dd/develop/atomist/lifecycle-automation/node_modules/zen-observable/lib/Observable.js:130:18)\n    at onNotify (/Users/dd/develop/atomist/lifecycle-automation/node_modules/zen-observable/lib/Observable.js:161:3)\n    at SubscriptionObserver.error (/Users/dd/develop/atomist/lifecycle-automation/node_modules/zen-observable/lib/Observable.js:220:7)\n    at /Users/dd/develop/atomist/lifecycle-automation/node_modules/apollo-link-http/src/httpLink.ts:163:20\n    at Promise.propagateAslWrapper (/Users/dd/develop/atomist/lifecycle-automation/node_modules/async-listener/index.js:502:23)\n    at Promise.__asl_wrapper (/Users/dd/develop/atomist/lifecycle-automation/node_modules/async-listener/glue.js:188:31)\n    at proxyWrapper (/Users/dd/develop/atomist/lifecycle-automation/node_modules/async-listener/index.js:527:23)\n    at /Users/dd/develop/atomist/lifecycle-automation/node_modules/async-listener/index.js:539:70\n    at /Users/dd/develop/atomist/lifecycle-automation/node_modules/async-listener/glue.js:188:31\n    at process._tickCallback (internal/process/next_tick.js:68:7)","error":{"graphQLErrors":[],"networkError":{"response":{"size":0,"timeout":0},"statusCode":400,"result":{"errors":[{"message":"Invalid query: Variable '$channelName': Null value not allowed for expected type 'String!'.","code":400}],"extensions":{"correlation_id":"dd26751d-c7b2-4468-9cf6-082311b041d8"}}},"message":"Network error: Response not successful: Received status code 400"}}
```
