### ISSUE TITLE
Message on bot join channel asks for org after user has already selected repo when more than one org is linked to team

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#25]
![image](https://user-images.githubusercontent.com/19268924/32381595-0d1253f8-c081-11e7-80b2-642f04640eaa.png)

This message should not need org mapped parameter and rather parse orgSlashRepo to get both org and repo, otherwise bot asks user to provide the org even though user just has selected both org and repo name

**Comment by cdupuis** [comment]
@tanya-coding I don't think this part has been moved over yet. It is still in enrollment-rugs.

**Comment by tanya-coding** [comment]
Sounds good. Let’s make sure we don’t migrate the bug over

**Comment by cdupuis** [comment]
Agreed. Let's keep this open to make sure we have a reminder to test this once we have that handler migrated.

**Comment by ddgenome** [comment]
This should be fixed in #33
