### ISSUE TITLE
The URL for BitBucket pull requests is incorrect

### ISSUE THREAD

**Issue by ddgenome** [atomist/lifecycle-automation#253]
When displaying a BitBucket PR, the link URL to the PR is missing the `projects` element.

For example:

`https://bitbucket/HOFF/bb6/pull-requests/1` provided (wrong)   
`http:s//bitbucket/projects/HOFF/repos/bb6/pull-requests/1` correct

**Comment by cdupuis** [comment]
Fixed in 910166a0202dc2aaf41e9967e172892bb841be3f
