### ISSUE TITLE
Send DM to reviewer on new commits to a PR

### ISSUE THREAD

**Issue by cdupuis** [atomist/lifecycle-automation#27]
When new commits to PRs that you are assigned as reviewer, we should send you a DM informing you about the new commit.

**Comment by cdupuis** [comment]
@Tapppi that is probably something you'd like to follow.

**Comment by Tapppi** [comment]
I think this is good, especially when combined with no branch commit messages and tt refresh PRs. Only concern is if branch commits are on and you get both branch commits on channel and dm from atomist 🤔 but don't know a way to detect whether user will see notification from other channel they are subscribed to.. I would guess that's not possible with slack api 😅
