### ISSUE TITLE
Re-create a PR message after 8hrs

### ISSUE THREAD

**Issue by cdupuis** [atomist/lifecycle-automation#28]
When updating commits or any other aspects of a PR it is important that we re-render the message after a certain ttl. Currently we are thinking 8hrs.

**Comment by cdupuis** [comment]
@Tapppi another one.

**Comment by Tapppi** [comment]
Yep I think this might be anything from 4hrs-24hrs. I'm looking to hold a questionnaire this week in our team and management to find out what they would prefer. Just to get a more informative decision for you, since this would need a sensible default.

**Comment by Tapppi** [comment]
Also, pr should be refreshed only if there has been a change? To avoid spam..

**Comment by Tapppi** [comment]
![image](https://user-images.githubusercontent.com/3275280/33145523-5a31b4ba-cfc9-11e7-9fcd-aa17c8bdebbd.png)

Holding a poll with the team on what the time interval should be, is it configurable? 😂

**Comment by cdupuis** [comment]
We can make it configurable.

**Comment by Tapppi** [comment]
I'll get back to you tomorrow with the results.

**Comment by Tapppi** [comment]
Or if this can be configured with `@atomist configure lifecycle` that would be perfect

**Comment by Tapppi** [comment]
Also, can the earlier messages about the PR be removed when it is repushed onto channel, to clean up history or something?
