### ISSUE TITLE
Is it possible to make all Atomist replies threaded?

### ISSUE THREAD

**Issue by mgcarrillo** [atomist/lifecycle-automation#284]
Perhaps this can be channel configurable, but basically, our Atomist end users would like to see all responses shown as a threaded reply to a command issued.  This helps keep the slack channels that our teams are using to deploy their apps a lot cleaner.  Thanks!

**Comment by cdupuis** [comment]
cc @slimslenderslacks

**Comment by cdupuis** [comment]
We can certainly make that work for commands and send all _response_ messages into a thread.

Could you provide some more details on which commands you want this enabled @mgcarrillo?

**Comment by mgcarrillo** [comment]
Based on some of our dev teams' feedback, they'd like to see responses to all Atomist commands as threads.  Here's an example:

![image](https://user-images.githubusercontent.com/17484151/56835755-57129580-6832-11e9-8014-8fac8a5ea994.png)

Hopefully that's not too general.  Thanks
