### ISSUE TITLE
Messages should not be sent to "null" users

### ISSUE THREAD

**Issue by dansmithy** [atomist/lifecycle-automation#286]
Not certain this is a lifecycle issue.

There was a message sent to chat address to `"user":{"name":null}`. Think this is because for MSTeams right now we can't guarantee that all chatids in the graph have a name. The message was a mention in a Github issue comment.

Should lifecycle handle this scenario and only send messages when a screenName can be found? Maybe we should support addressing users (and channels?) by id rather than name.

**Comment by cdupuis** [comment]
Issue moved to atomist/automation-client#530
