### ISSUE TITLE
Use Branch creation as start of PR lifecycle

### ISSUE THREAD

**Issue by cdupuis** [atomist/lifecycle-automation#29]
Right now we start the PR lifecycle with the creation of PRs. It is proposed to start the PR lifecycle with the creation of a branch. This is especially important for configurations where commits to non-default branches aren't shown. 

The creation of the PR would then re-write the branch message with the actual PR.

**Comment by cdupuis** [comment]
cc @Tapppi

**Comment by Tapppi** [comment]
As simple as that 👍
