### ISSUE TITLE
Chat user name with space has dash inserted incorrectly

### ISSUE THREAD

**Issue by dansmithy** [atomist/lifecycle-automation#291]
A Slack message like this: 

`{"text": "Linked *owner/repo* to <#channel-id> and invited you to the channel."}` 

was addressed to:

`{"user_agent": "slack", "slack" : {"team" {"id" : "TEAMID"}, "user": {"name": "Danny-Smith"}}}`

the name should be `Danny Smith` with a space. This fails looking us user id, so the message does not get posted.

**Comment by cdupuis** [comment]
The user name for the message destination is extracted from the msgId parameter of the incoming command handler request which is created via a button press on from the following message as sent by lifecycle

```
'{"api_version":"1","correlation_id":"47e57bb9-fb0c-4e12-977a-a4f880967665","team":{"id":"AN5BQH6A0","name":"Danny Algol"},"event":"PushToUnmappedRepo","destinations":[{"user_agent":"s***k","slack":{"team":{"id":"19:2f7c6dc3f44542e499a78749050660f6@thread.skype"},"user":{"name":"Danny Smith"}}}],"id":"user_message/unmapped_repo/Danny Smith/dansmithy/node-start-jul5","timestamp":1562358147065,"post_mode":"ttl","content_type":"application/x-atomist-slack+json","body":"{\"attachments\":[{\"pretext\":\"Want to put me to work on <https://github.com/dansmithy/node-start-jul5|dansmithy/node-start-jul5> in a channel?\",\"fallback\":\"Want to put me to work on dansmithy/node-start-jul5 in a channel?\",\"text\":\"\",\"mrkdwn_in\":[\"pretext\"],\"actions\":[{\"text\":\"Create #node-start-jul5\",\"type\":\"button\",\"name\":\"automation-command::createchannel-0\",\"style\":\"primary\"},{\"text\":\"Other channel...\",\"type\":\"select\",\"name\":\"automation-command::createchannel-1\",\"options\":[{\"text\":\"General\",\"value\":\"General\"}]}],\"callback_id\":\"cllbck1\"},{\"fallback\":\"or '/invite @atomist' me to a relevant channel and type\\n'@atomist repo owner=dansmithy name=node-start-jul5'\",\"text\":\"or `/invite @atomist` me to a relevant channel and type\\n`@atomist repo owner=dansmithy name=node-start-jul5`\",\"mrkdwn_in\":[\"text\"]},{\"text\":\"This is the last time I will ask you about *dansmithy/node-start-jul5*. You can stop receiving similar suggestions for all repositories by clicking the button below.\",\"fallback\":\"This is the last time I will ask you about dansmithy/node-start-jul5. You can stop receiving similar suggestions for all repositories by clicking the button below.\",\"mrkdwn_in\":[\"text\"],\"actions\":[{\"text\":\"All Repositories\",\"type\":\"button\",\"name\":\"automation-command::setuserpreference-2\"}],\"callback_id\":\"cllbck2\"}]}","actions":[{"id":"createchannel-0","command":"CreateChannel","parameters":[{"name":"channel","value":"node-start-jul5"},{"name":"apiUrl","value":"https://api.github.com/"},{"name":"owner","value":"dansmithy"},{"name":"repo","value":"node-start-jul5"},{"name":"msgId","value":"user_message/unmapped_repo/Danny Smith/dansmithy/node-start-jul5"}]},{"id":"createchannel-1","parameter_name":"channel","command":"CreateChannel","parameters":[{"name":"apiUrl","value":"https://api.github.com/"},{"name":"owner","value":"dansmithy"},{"name":"repo","value":"node-start-jul5"},{"name":"msgId","value":"user_message/unmapped_repo/Danny Smith/dansmithy/node-start-jul5"}]},{"id":"setuserpreference-2","command":"SetUserPreference","parameters":[{"name":"key","value":"dm"},{"name":"name","value":"disable_for_mapRepo"},{"name":"value","value":"true"},{"name":"label","value":"'Map Repository To Channel' direct messages disabled"},{"name":"id","value":"user_message/unmapped_repo/Danny Smith/dansmithy/node-start-jul5"}]}]}
```

As seen the msgId parameters is defined as `{"name":"msgId","value":"user_message/unmapped_repo/Danny Smith/dansmithy/node-start-jul5"}`

But when the button is pressed, the msgId parameters comes back as:

```
{"mapped_parameters":[{"name":"teamId","value":"19:2f7c6dc3f44542e499a78749050660f6@thread.skype"},{"name":"owner","value":"dansmithy"},{"name":"apiUrl","value":"https://api.github.com/"},{"name":"provider","value":"zjlmxjzwhurspem"},{"name":"userId","value":"29:1ORiPG6c_f820gDGg"}],"secrets":[],"command":"CreateChannel","source":{"user_agent":"msteams","msteams":{"team":{"id":"19:2f7c6dc3f44542e499a78749050660f6@thread.skype","name":"Danny Staging Algol"},"channel":{"id":"29:1ORiPG6FrUnOP6FSxeYoveM_f820gDGg","name":"Danny Smith","conversation":{"conversationType":"personal","id":"a:1kzWKRWqr0K_o4sTH9UKKsKLW4g"}},"user":{"id":"29:1ORiPG6FrUnOP6FSxeYoveMd9vVjuqUySp0Tc_f820gDGg","name":"Danny Smith"},"thread_ts":"a:1kzWKRWqrgk4VCNE9F6ZZ0K_o4sTH9UKKsKLW4g","service_urls":["https://smba.trafficmanager.net/amer/"]},"interaction_id":"19:2f7c6dc3f44542e499a78749050660f6@thread.skype_f:2873633060755430093"},"correlation_id":"d0f16e17-cfe9-40a0-b80f-559944dbda2b","team":{"id":"AN5BQH6A0","name":"Danny Algol"},"automation":{"name":"@atomist/lifecycle-automation","version":"1.0.0"},"api_version":"1","parameters":[{"name":"channel","value":"node-start-jul5"},{"name":"repo","value":"node-start-jul5"},{"name":"msgId","value":"user_message/unmapped_repo/Danny-Smith/dansmithy/node-start-jul5"}]}
```

or `{"name":"msgId","value":"user_message/unmapped_repo/Danny-Smith/dansmithy/node-start-jul5"}`.

This msgId is wrongly sent down to lifecycle and is the reason why we address the message to `Danny Smith`. 

I'm closing this as the error is not in lifecycle as it is not permitted to change the msgIds as they some times have some actual meaning. 

cc @dansmithy

**Comment by alice-atmtest** [comment]
@cdupuis Had no idea those msgIds were used like that :)

The space is converted to a dash to work around a previous issue where the msgId cannot contain spaces (due to the pattern on the command). Remember this one: https://github.com/atomist/automation-client/issues/539 ? Not sure if that change has made it to production yet (I can check).

However, the fix you put in replace a space with an underscore. Doesn't that give us the same problem for a user name with spaces? I'd like to find a solution to this, otherwise MSTeams is not going to work for some of these commands.

**Comment by dansmithy** [comment]
@cdupuis Had no idea those msgIds were used like that :)

The space is converted to a dash to work around a previous issue where the msgId cannot contain spaces (due to the pattern on the command). Remember this one: atomist/automation-client#539 ? Not sure if that change has made it to production yet (I can check).

However, the fix you put in replace a space with an underscore. Doesn't that give us the same problem for a user name with spaces? I'd like to find a solution to this, otherwise MSTeams is not going to work for some of these commands.

**Comment by cdupuis** [comment]
Remember that we rolled back the _msgId replace space change_ you referenced above and fixed the pattern instead? That’s all in prod. 

I’m not sure where that replace is happening now but it certainly is breaking.

**Comment by dansmithy** [comment]
@cdupuis Aaah thanks that's good. I will remove the replacement and see if that fixes the issue.
