### ISSUE TITLE
External Build Goals prompt for restart

### ISSUE THREAD

**Issue by ipcrm** [atomist/lifecycle-automation#294]
For build goals with `externalTool` fulfillment, LIfeycle should not prompt to restart that goal.   

Currently it does:

![image](https://user-images.githubusercontent.com/10358528/62011904-ea6aa800-b14c-11e9-8d7b-261a940c78e5.png)

**Comment by cdupuis** [comment]
Issue moved to atomist/sdm-pack-build#42
