### ISSUE TITLE
PR lifecycle lists wrong commits when base branch is not master

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#39]
Example PR (contains only 1 commit): https://github.com/atomist/end-user-documentation/pull/204

As rendered:

![image](https://user-images.githubusercontent.com/19268924/32681250-28abcadc-c634-11e7-8ab7-67889c08a613.png)

**Comment by cdupuis** [comment]
The data that is being rendered is what we are getting from the subscription. I have the logs. We should close this here and move to API. 

cc @tanya-coding
