### ISSUE TITLE
Show action buttons in slack DMs

### ISSUE THREAD

**Issue by jrday** [atomist/lifecycle-automation#48]
Not sure if this applies to all DMs from the bot, or just the issue message I saw, but I'm not getting the buttons here:

<img width="637" alt="screen shot 2017-11-19 at 13 26 25" src="https://user-images.githubusercontent.com/774714/32996709-fc1e0454-cd3a-11e7-9c78-d7e98b772c97.png">

But in the mapped channel, they do show. I just happened to be looking at the notification in DM from @atomist and thought I would like to reply comment right there.

<img width="623" alt="screen shot 2017-11-19 at 15 05 08" src="https://user-images.githubusercontent.com/774714/32996715-0e3edd20-cd3b-11e7-91d3-ed37756df0a2.png">

**Comment by cdupuis** [comment]
I've added command and +1 buttons to issue and issue comment mentions. not sure what others we would want.

I'll defer to you @jrday and @WillGardella for that.

**Comment by WillGardella** [comment]
What was the rationale for limiting the available buttons in this situation? Save space, assuming that mentions are like an "FYI only" thing?

**Comment by cdupuis** [comment]
> What was the rationale for limiting the available buttons in this situation? Save space, assuming that mentions are like an "FYI only" thing?

Yeah, mostly keep those DMs as small as possible.
