### ISSUE TITLE
installGitHubRepoWebHook should update owner mapped parameter 

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/lifecycle-automation#50]
The new foreign key should be:
`atomist://github/repository/owner?user=true`

This will behave slightly different than the current mapped parameter, in that it will populate the drop-down with a User org even in cases where the team has already enrolled one Organization.

**Comment by slimslenderslacks** [comment]
@cdupuis support for this is in staging now.  I would like to test this flow end to end.  @jessitron this is to make sure that we can allow users to link channels associated with User Repos even if that team has a GitHub Organization enrolled as well.

**Comment by cdupuis** [comment]
Starting to add this: https://github.com/atomist/automation-client-ts/commit/2a427422a48e6b4e57dfe5a24e6de642167bf441

cc @slimslenderslacks, if I released that to prod, would it fail without the backend changes promoted yet?

**Comment by cdupuis** [comment]
cc @slimslenderslacks ?

**Comment by slimslenderslacks** [comment]
changes to support this are in prod now.
