### ISSUE TITLE
Reposting large PR message on branch deleted generates noise in channel

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#54]
We've discussed updating bot to handle old message deletion when we repost message after TTL expires but that will not completely solve this issue. We should really either not post a message on branch delete or make it really small and just indicate that branch was deleted.

**Comment by cdupuis** [comment]
When the branch gets deleted, we are only showing the PR title and body. No commits etc. How much shorter should it be cc @tanya-coding?

**Comment by tanya-coding** [comment]
@cdupuis this was from conversation discussion with kyyti:

> complaint about PR messages being reposted if the branch gets deleted? Gotten 2 complaints about that now :smile: The PR messages are pretty big, so it's noticeable. Another cool thing would be to remove the old PR message when new one gets posted, and also tell changes after last post (number of commits, or why it was reposted?)

I can imagine that PR body can be quite big. I would prefer not to get any messages when branch is deleted (or be able to enable/disable). If we do post a message I would rather see "Branch deleted" than just see PR show up again - that is a bit confusing.

**Comment by cdupuis** [comment]
I'd say we do update the PR again with "update_only" to remove the Delete Branch button and post a branch deletion. That might work. But only if the PR doesn't show up again even if the TTL is expired. I can't remember if that's how update_only works.

**Comment by tanya-coding** [comment]
update_only would prevent message from reposting (assuming we still hold on to previous message) but I'm not sure it's ideal here either. If commits keep coming to a long living PR (which might happen when team uses "develop" branches for next release for example) we want to repost a PR message (and bot could handle deletion of old one with the enhancement we've discussed), but if the PR change is branch deleted I would imagine most team would either not care or would want to clearly see that branch is deleted not that PR has been touched.

Also, possibly we don't show PR body once PR is merged.

**Comment by cdupuis** [comment]
I honestly don't know what I should do now. Everything I'd like to do isn't possible right now. Here's the ideal:

* Rewrite the PR so that Delete Branch buttons disappears.
* Post a new branch deletion message

The 2nd is totally possible but the 1st one isn't: The PR currently has a TTL so every update would bring the message back potentially if the TTL is expired. But for this case we don't want the message to come back, only for the button to disappear.

**Comment by tanya-coding** [comment]
The first one can be accomplished with "update_only" - I just wouldn't apply that setting to all PR related messages but rather ones we don't want to cause repost (e.g. when PR is merged and we want to remove button from older message). Is it too tricky to apply update_only only for some parts of PR lifecycle?

**Comment by cdupuis** [comment]
No, it is not tricky. But the initial PR message was posted with TTL and the update_only would potentially come in after TTL. Would that repost the message or only update?

**Comment by tanya-coding** [comment]
update_only will only update message regardless if original message had TTL or not and regardless if we can find an older message or not, in other words we should never post a new message when update_only is set. What could happen with older messages is that we won't even update them once we purge them from storage.
