### ISSUE TITLE
Fix images and emojis

### ISSUE THREAD

**Issue by cdupuis** [atomist/lifecycle-automation#68]
Some is going on with some of the images we are using:

<img width="762" alt="icons" src="https://user-images.githubusercontent.com/206707/33736337-1cfca90e-db47-11e7-8a4b-d89a2189b176.png">

**Comment by ddgenome** [comment]
Do we have any influence over the size of those?

**Comment by cdupuis** [comment]
Yeah, that is me messing up the icons: 

https://images.atomist.com/rug/atomist_build_started.gif vs https://images.atomist.com/rug/pulsating-circle.gif
