### ISSUE TITLE
Request PR summary when it hasn't changed recently

### ISSUE THREAD

**Issue by jessitron** [atomist/lifecycle-automation#73]
add command to resurrect the PR lifecycle message on demand

**Comment by cdupuis** [comment]
@jessitron the command should show which PR? Or present a list of PRs to select from?

**Comment by jessitron** [comment]
I suspect owner/repo/PR as parameters, so it’s easy to supply the PR number on a mapped repo. It’s going to appear only in linked channels anyway

**Comment by cdupuis** [comment]
Ok, cool. That’s easy. We have that for issue already. So adding this will not be hard.

**Comment by jessitron** [comment]
Emma requests a status on this. If you want I can implement it (any pointers welcome)

**Comment by ddgenome** [comment]
No work on this so far.

**Comment by cdupuis** [comment]
@jessitron take a look at https://github.com/atomist/lifecycle-automation/blob/master/src/handlers/command/github/DisplayGitHubIssue.ts for a similar feature for displaying GitHub Issues.

Once you have the `DisplayGitHubPullRequest` command implemented we should also add that to the Details button of `SearchGitHubRepositoryIssues`.
