### ISSUE TITLE
Want to put me to work -> Go Ahead doesn't work in personal GH account

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#87]
Example correlation ID: a82d0a22-2614-4450-bd5c-bc4d53344240

For one of my test teams that only has a personal GH account linked (after installing repo webhooks) when I commit to an unmapped repo, I receive "What to put me to work?" message. When I click "Go Ahead" it fails:

```
Unable to run command
Unsuccessfully invoked command-handler CreateChannel of @atomista/lifecycle-automation@0.2.14-20180105095009
Correlation ID: a82d0a22-2614-4450-bd5c-bc4d53344240
```

**Comment by cdupuis** [comment]
The createChannel mutation changed its returns data structure. It now returns `{"createSlackChannel":{"id":"C76REP44R","name":"tanyatest3"}}` which is a change to conform to the spec but breaks current handler code.
