### ISSUE TITLE
Repo linking doesn't work for a brand new team

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#90]
Example correlation ID: 0c0c7d03-64e1-4f85-9fa0-0d56acc8f298

Command returns success status but no linking happens and no message about repo being now linked arrives to channel. This is a brand new team in staging (it will not have Team->ChatTeam established if that matters). 

lifecycle-automation version 0.2.14-20180109175013.

**Comment by cdupuis** [comment]
Lifecycle in staging hasn’t been updated for the new mutations. It is all still on a branch. This is likely just because the mutation isn’t called with the correct parameters.

**Comment by tanya-coding** [comment]
@cdupuis wouldn't that mean that we have the same issue in prod for new teams? Is that not the version we use currently in prod?

**Comment by cdupuis** [comment]
No, the mutations are not yet in prod. We have to sync a rollout.
