### ISSUE TITLE
Parse image URLs in issue body and put them into separate attachments using Slack `image_url` field

### ISSUE THREAD

**Issue by tanya-coding** [atomist/lifecycle-automation#97]
It would be nice if we displayed images right inside issue message when we detect them. We should probably limit number of images we attach to some reasonable number.

For example (you will need to click blue arrow to show/close attachment):

https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22Platypus%20opened%20a%20new%20issue%3A%22%2C%22attachments%22%3A%5B%7B%22mrkdwn_in%22%3A%5B%22text%22%5D%2C%22text%22%3A%22Big%20bug.%20Something%20is%20not%20working%2C%20see%20screenshot%3A%20%5Cnhttps%3A%2F%2Fuser-images.githubusercontent.com%2F19268924%2F34843690-cfad14dc-f6d4-11e7-9464-ad4a922400ff.png%22%7D%2C%7B%22text%22%3A%22Attached%20image%22%2C%22image_url%22%3A%22https%3A%2F%2Fuser-images.githubusercontent.com%2F19268924%2F34843690-cfad14dc-f6d4-11e7-9464-ad4a922400ff.png%22%7D%5D%7D

**Comment by cdupuis** [comment]
Probably the same for comments. I’ll limit this to 3 images.
